### ISSUE TITLE
Consistent Time Zone On Pair Request

### ISSUE THREAD

**Issue by Natblow** [agency-of-learning/PairApp#420]
### Problem

It is a bit confusing what exact time the pair request is for. 

![image](https://github.com/agency-of-learning/PairApp/assets/85266997/f429c114-fe3e-42d6-a7f7-1fe9a7264a99)

You need a 2 second mental pause to figure out the first time. We could improve this so that it feels more natural.

#### On the Form

1.  Have a consistent time format when selecting the date and display the date. Currently when we select the time we have the european 24hours format but then everything display as the AM/PM format.
2. Optional: Making more precision of the time zone of the other developer by adding a sentence such as "For the time zone of the invitee, it will be at *date*"  if his/hers timezone is different than yours. 

#### On Index

1. Always show the user's time zone next to the time. For example, in the list of all your Pair Requests : 

![image](https://github.com/agency-of-learning/PairApp/assets/85266997/19ab34d1-3d39-4f2b-a8eb-7b707863a5ca)

### Additional info

Form is on `app/views/pair_requests/_form.html.erb`
Index is on `app/views/pair_requests/index.html.erb`

**Comment by afogel** [comment]
I think another aspect of this that makes it difficult is that the two columns are not consistent/they're spread out too much. I think that keeping where to look predictable and consistent, as well as what the format of the date looks like, will reduce cognitive load when trying to make these changes.

**Comment by dpaola2** [comment]
I like the initiative of proactively identifying this as a UX issue and suggesting a solution.

**Comment by afogel** [comment]
BE HUNGRY! ;)

**Comment by jp524** [comment]
The format for input type `datetime-local` as seen below is determined by the user's browser locale. That explains why @Natblow's input and mine look different.
![image](https://github.com/agency-of-learning/PairApp/assets/85654561/5b2a45fe-1cf7-4df2-95b3-5b8f57aa3905)

Since it cannot be changed, I will simply ensure that other DateTimes on the page are displayed consistently in the format yyyy-mm-dd hh:mm a.m/p.m. I believe this is standard for North America.
