### ISSUE TITLE
Bug: Flash messages not closing

### ISSUE THREAD

**Issue by JoshDevHub** [agency-of-learning/PairApp#78]
There's a bug with flash messages closing. The bug is present for Google Chrome and Safari.

## To Recreate:
1. Start the dev server, visit `localhost:3000`, and login
    - Assuming you've seeded the database properly, you can login with email: `user1@user.com`, password: `password`
2. Try closing the flash message for "Signed in successfully". You should see that it doesn't properly close.

## To Fix:
Make sure flash messages close when you click on their 'X' button. This problem may be related to the `TypeError` that shows up in the browser console, and fixing it may require some adjustments to the way the app's Stimulus controllers are configured.

**Comment by elhalvers** [comment]
I can work on this : )

**Comment by elhalvers** [comment]
I have solved the primary issue and am getting the desired behavior. I kind of want to clean it up a bit.

The fundamental issue is that there is a `data-action="alert#close"` called on the button in the [flash partial](https://github.com/agency-of-learning/PairApp/blob/main/app/views/layouts/_flash.html.erb#LL4C13-L4C38) but there is no `alert.js` Stimulus controller or `#close` action defined so I added those.

Also, I believe the `tailwindcss-stimulus-components` information should be in `app/javascript/controllers/application.js` instead of in [`app/javascript/controllers/index.js`](https://github.com/agency-of-learning/PairApp/blob/main/app/javascript/controllers/index.js#L1-L15C1)

I moved them in my working branch but I wanted to read up on Stimulus a little more.

Let me know if you want me to a push a draft PR before I finish studying.

Thank you!

: )

**Comment by elhalvers** [comment]
I will delete the unneeded 'alert' controller' and push the branch again and then work on testing : )
